let text="rose,sunflower,jasmine and lilly"
const extract=text.slice(5,14)
console.log(extract)
const extract2=text.slice(-17,-10)
console.log(extract2)
const extract1=text.substring(5,14)
console.log(extract1)
const extract3=text.substr(5,9)
console.log(extract3)
console.log(text.toUpperCase())
console.log(text.toLowerCase())
let text1="apple,banana,pear and mango"
console.log(text.concat(" ",text1))
console.log(text.replace(/rose/ig,"tulips"))
// console.log(text)
console.log(text.replaceAll("rose","tulips"))
let str="   hello  "  
console.log(str.trim())
console.log(str)
console.log(str.trimStart())
console.log(str.trimEnd())
// console.log(text[0])
// console.log(text.charAt(0))
str="hello"
console.log(str.padStart(10,"#"))
console.log(str.padEnd(10,"#"))
console.log(str.split(""))
console.log(text.indexOf("jasmine"))
console.log(text.lastIndexOf("rose"))
